kmutnbtrack/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from kmutnbtrackapp import views

urlpatterns = [
    path('', include('kmutnbtrackapp.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('privacy/', TemplateView.as_view(template_name="Page/privacy.html"), name='privacy_policy'),
    path('admin/kmutnbtrackapp/lab/qrcode/<str:lab_hash>/', views.generate_qr_code, name='generate_qr_code'),
    path('lab/<str:lab_hash>/qrcode', views.generate_qr_code, name='show_qr_code'),
    path('admin/kmutnbtrackapp/lab/view/<str:lab_hash>/', views.view_lab, name='view_lab'),
    path('admin/dashboard/', views.call_dashboard, name='dashboard'),
    path('admin/history/search/riskpeople/', views.risk_people_search, name='risk_people_search'),
    path('admin/history/search/riskpeople/<int:page>', views.risk_people_search),
    path('admin/history/search/riskpeople/notify_confirm/<str:where>', views.notify_confirm, name='notify_confirm'),
    url(r'^admin/history/search/riskpeople/notify/(?P<mode>.+)/(?P<keyword>.+)/$', views.notify_user, name='notify'),
    path('admin/history/search/riskpeople/download_risk_csv/', views.export_risk_csv, name='download_risk_csv'),
    path('admin/history/search/history/', RedirectView.as_view(url='/admin/history/search/history/1/', permanent=False),
         name='history_search'),
    path('admin/history/search/history/<int:page>/', views.history_search, name="history_search_function"),
    path('admin/history/search/history/download_normal_csv/', views.export_normal_csv, name='download_normal_csv'),
    path('admin/backup', views.backup, name='backup'),
    path('admin/', admin.site.urls, name='admin'),
    path('staff_signup/', views.staff_signup, name="staff_signup"),
    path('auth_head/<uid_b64>/<token>/', views.auth_head, name='auth_head'),
    path('auth_staff/<uid_b64>/<token>/', views.auth_staff, name='auth_staff'),
]

kmutnbtrackapp/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = "kmutnbtrackapp"

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/<str:lab_hash>/', views.signup_api, name='signup'),
    path('login/', views.login_api, name="login"),
    path("logout/", views.logout_api, name="logout"),
    path('lab/', RedirectView.as_view(url="/", permanent=False)),
    path('lab/<str:lab_hash>/', views.lab_home_page, name='lab_home'),
    path('home/', views.home, name='home'),
    path('check_in/<str:lab_hash>/', views.check_in, name='check_in'),
    path('check_out/<str:lab_hash>/', views.check_out, name='check_out'),
    path('api/addfeedback/', views.add_feedback_api, name='add_feedback')
]

kmutnbtrackapp/models.py
import random

from django.contrib.auth.models import User
from django.db import models


# Create your models here.

def create_id():
    return random.getrandbits(32)


class Lab(models.Model):
    name = models.CharField(max_length=60, blank=True, null=True)
    max_number_of_people = models.IntegerField(blank=True, default=20)
    hash = models.CharField(max_length=16, primary_key=True, default=create_id)

    def __str__(self):
        return self.name


class Person(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, default="", blank=True)
    last_name = models.CharField(max_length=50, default="", blank=True)
    email = models.EmailField(default="", blank=True)
    student_id = models.CharField(max_length=13, default="", blank=True)
    is_student = models.BooleanField(default=False)
    ask_feedback = models.BooleanField(default=False)

    def __str__(self):
        return self.first_name + " " + self.last_name


class History(models.Model):
    #   id_by_date = models.อะไรสักอย่าง
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE)
    checkin = models.DateTimeField(null=True, auto_now_add=True)
    checkout = models.DateTimeField(null=True)
    exceeded_limit = models.BooleanField(default=False)

    def __str__(self):
        return self.lab.name


class LabPending(models.Model):
    staff_user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=60, blank=True, null=True)
    max = models.IntegerField(blank=True, default=20)
    lab_head_first_name = models.CharField(max_length=60, blank=True, null=True)
    lab_head_last_name = models.CharField(max_length=60, blank=True, null=True)
    head_email = models.CharField(max_length=60, blank=True, null=True)

    def __str__(self):
        return self.name


class Feedback(models.Model):
    star = models.IntegerField(default=0)
    text = models.TextField(default="")
    is_student = models.BooleanField(default=False)

    def __str__(self):
        return self.text

kmutnbtrackapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from captcha.fields import ReCaptchaField

from .models import *


class SignUpForm(UserCreationForm):
    captcha = ReCaptchaField()
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=150)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'email',)

kmutnbtrackapp/views/admin_views.py
"""
Imports should be grouped in the following order:

1.Standard library imports.
2.Related third party imports.
3.Local application/library specific imports.
"""

import csv
import qrcode
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont

from django.contrib import messages
from django.core import management
from django.core.mail import EmailMessage
from django.core.paginator import Paginator
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect, HttpResponse
from django.utils.http import urlsafe_base64_decode
from django.shortcuts import redirect
from django.utils.encoding import force_bytes
from django.contrib.auth import get_user_model
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.models import Group, Permission

from kmutnbtrackapp.dashboard import *
from kmutnbtrackapp.views.help import *
from kmutnbtrackapp.views.help import tz


@superuser_login_required
def history_search(request, page=1):
    """Received from the client and searched for information from the server and then sent back to the client"""
    keyword = request.GET.get('keyword', '')
    start = request.GET.get('from', '')
    stop = request.GET.get('to', '')
    mode = request.GET.get('mode', '')
    histories, all_history = query_search(mode, keyword, start, stop, "normal")

    p = Paginator(all_history, 36)
    num_pages = p.num_pages
    shown_history = p.page(page)

    split_url = request.get_full_path().split("/")
    if page == 1:
        prev_url = None

        if num_pages != 1:
            split_url[-2] = "2"
            next_url = "/".join(split_url)
        else:
            next_url = None

    elif page == num_pages:
        split_url[-2] = str(num_pages - 1)
        prev_url = "/".join(split_url)

        next_url = None

    else:
        split_url[-2] = str(page - 1)
        prev_url = "/".join(split_url)

        split_url[-2] = str(page + 1)
        next_url = "/".join(split_url)
    return render(request, 'admin/history_search.html',
                  {'shown_history': shown_history,
                   'keyword': keyword,
                   'select_mode': mode,
                   'start': start,
                   'stop': stop,
                   'current_page_number': page,
                   'prev_url': prev_url,
                   'next_url': next_url,
                   })


@supervisor_login_required
def view_lab(request, lab_hash):
    this_lab = Lab.objects.get(hash=lab_hash)
    if not (request.user.is_superuser or request.user.groups.filter(name=this_lab.name).exists()):
        return render(request, 'Page/error.html', {"error_message": "Permission denied"})
    now_datetime = datetime.datetime.now(tz)
    midnight_time = now_datetime.replace(hour=23, minute=59, second=59, microsecond=0)
    current_people = History.objects.filter(lab=this_lab,
                                            checkout__gte=now_datetime,
                                            checkout__lte=midnight_time)
    if request.method == "POST" and request.POST.get('confirm', '') == "ยืนยัน":
        for person in current_people:
            out_local_time = datetime.datetime.now(tz)
            person.checkout = out_local_time
            person.save()
        messages.info(request, 'All the people in %s has been cleared successfully' % this_lab.name)
        return HttpResponseRedirect('/admin/kmutnbtrackapp/lab/')
    elif request.method == "POST" and request.POST.get('confirm', '') != "ยืนยัน":
        return render(request, 'admin/notify_confirm.html', {'clear_lab': True, 'this_lab': this_lab, 'fail': True})
    return render(request, 'admin/view_lab.html', {'this_lab': this_lab, 'shown_history': current_people})


@superuser_login_required
def export_normal_csv(request):
    """export file csv log to user"""
    mode = request.GET.get('mode', '')
    keyword = request.GET.get('keyword', '')
    start = request.GET.get('from', '')
    stop = request.GET.get('to', '')
    histories, all_history = query_search(mode, keyword, start, stop, "normal")
    response = HttpResponse(content_type='text/csv')
    writer = csv.writer(response)
    writer.writerow(['Student ID', 'Person Name', 'Phone number', 'Lab Name', 'Check in time', 'Check out time'])
    for user in all_history:
        user = list(user)
        user[4] = user[4].astimezone(tz)
        user[5] = user[5].astimezone(tz)
        writer.writerow(user)
    response['Content-Disposition'] = 'attachment; filename="file_log.csv"'
    return response


@superuser_login_required
def risk_people_search(request):
    """Received from the client filter data and sent back to client"""
    risk_people_data = "EMPTY"
    keyword = ""
    mode = ""
    if request.GET:  # if request has parameter
        mode = request.GET.get('mode', '')
        keyword = request.GET.get('keyword', '')
        risk_people_data, risk_people_notify = filter_risk_user(mode, keyword)

    return render(request, 'admin/risk_people_search.html',
                  {'shown_history': risk_people_data,
                   'keyword': keyword, 'select_mode': mode,
                   })


def generate_qr_code(request, lab_hash):
    lab_name = Lab.objects.get(hash=lab_hash).name
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=20,
        border=0,
    )
    qr.add_data(f"https://labtrack.cony.codes/lab/{lab_hash}/")
    qr.make()
    img_qr = qr.make_image()

    img_frame = Image.open("kmutnbtrackapp/static/qrcode_src/QR_frame.png", 'r')

    pos = (80 + 30, 295 + 19)
    img_frame.paste(img_qr, pos)

    drawer = ImageDraw.Draw(img_frame)

    font_size = 66
    font = ImageFont.truetype("kmutnbtrackapp/static/qrcode_src/GOTHICB.ttf", font_size)
    ascent, descent = font.getmetrics()
    (width, baseline), (offset_x, offset_y) = font.font.getsize(lab_name)

    if len(lab_name) > 30:
        drawer.text((100, 190), "Lab name too long!!!", (128, 0, 0), font=font)

    elif len(lab_name) > 14:  # long name -> reduce font size
        while width >= 580:
            font_size -= 1
            font = ImageFont.truetype("kmutnbtrackapp/static/qrcode_src/GOTHICB.ttf", font_size)
            ascent, descent = font.getmetrics()
            (width, baseline), (offset_x, offset_y) = font.font.getsize(lab_name)

    drawer.text((400 - int((width + 74) / 2) + 74, 220 - ascent), lab_name, (0, 0, 0), font=font)

    flag_img = Image.open("kmutnbtrackapp/static/qrcode_src/maps-and-flags.png", 'r')
    flag_img = flag_img.resize((74, 74), resample=Image.LANCZOS)
    pos = (int(400 - (width + 74) / 2 - 3),
           int(220 - ascent + offset_y + (ascent - offset_y) / 2 - 74 / 2))
    img_frame.paste(flag_img, pos, mask=flag_img.split()[1])

    img_frame.save(f'media/{lab_name}_qrcode.png', "PNG", quality=100)
    with open(f'media/{lab_name}_qrcode.png', "rb") as f:
        response = HttpResponse(f.read(), content_type="image/png")
        response['Content-Disposition'] = 'inline; filename=' + f'media/{lab_name}_qrcode.png'
        return response


@superuser_login_required
def export_risk_csv(request):
    """export file risk user csv log to user"""
    mode = request.GET.get('mode', '')
    keyword = request.GET.get('keyword', '')
    if keyword != "":
        risk_people_data, not_use = filter_risk_user(mode, keyword)
        response = HttpResponse(content_type='text/csv')
        writer = csv.writer(response)
        writer.writerow(
            ['Student ID', 'Person Name', 'Phone number', 'Lab Name', 'Check in time', 'Check out time'])
        for user in risk_people_data:
            user = list(user)
            user[4] = user[4].astimezone(tz)
            user[5] = user[5].astimezone(tz)
            writer.writerow(user)
        response['Content-Disposition'] = 'attachment; filename="Risk Log.csv"'
        return response
    else:
        return redirect(risk_people_search)


@superuser_login_required
def notify_confirm(request, where):
    lab_hash = request.GET.get('lab_hash', '')
    if not lab_hash == '':
        this_lab = Lab.objects.get(hash=lab_hash)
    if where == 'risk_people_search':
        mode = request.GET.get('mode', '')
        keyword = request.GET.get('keyword', '')
        if keyword != "":
            return render(request, 'admin/notify_confirm.html', {'mode': mode,
                                                                 'keyword': keyword,
                                                                 'send_email': True,
                                                                 })
        else:
            return redirect(risk_people_search)
    elif where == 'clear_lab':
        return render(request, 'admin/notify_confirm.html', {'clear_lab': True, 'this_lab': this_lab})


@superuser_login_required
def notify_user(request, mode, keyword):
    confirm = request.POST.get('confirm', '')
    if request.method == "POST" and confirm == "ยืนยัน":
        risk_people_data, risk_people_notify = filter_risk_user(mode, keyword)
        # remove duplicate user'info
        user_info = []
        for each_list in risk_people_notify:
            std_id = each_list[0]
            name = each_list[1]
            email = each_list[2]
            temp_list = [std_id, name, email]
            for each in risk_people_notify:
                if each[1] == name and each[3] not in temp_list:
                    temp_list.append(each[3])
            user_info.append(tuple(temp_list))
        risk_people_notify = set(user_info)

        user_data = {}
        user_email = []
        for each_user in risk_people_notify:
            student_id = each_user[0]
            first_last_name = each_user[1]
            each_user_email = each_user[2]
            if each_user_email != '':
                user_email.append(each_user_email)
                lab_name = ''

kmutnbtrackapp/templates/Page/check_out_before_due_new.html
{% extends 'Page/page_base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static '/css/check_out_before_due.css'%}">
{% endblock %}

{% block script %}
<script type="text/javascript"></script>
<script>
    let csrf_token = '{{csrf_token}}';
    const checkout_url = "{% url 'kmutnbtrackapp:check_out' last_lab.hash  %}";
function checkout(){
    fetch(checkout_url,{
        method: "POST",
        headers: { "X-CSRFToken": csrf_token },
    })
    .then(response =>{ 
        return response.text()
    })
    .then(html =>{
        document.getElementsByTagName("body")[0].innerHTML = html
    })
}
</script>
{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static '/css/lab_checkin_successful.css'%}">
<!-- navbar room name-->
<nav class="navbar navbar-dark" style="background-color: #1261A0;">
    <a class="navbar-brand" href="#">
        <img src="{% static 'images/logo.png' %}" width="30" height="auto" class="d-inline-block" alt="" loading="lazy">
        {{ last_lab.name }}
    </a>
    <div class="btn-group btn-username">
        <button type="button" class="btn dropdown-toggle dropdown-user" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="{% static 'images/people.png' %}" width="22" alt="username_pic" >
        </button>
        <div class="dropdown-menu dropdown-menu-right">
            <button class="dropdown-item disabled" type="button">{{ request.user.first_name }}</button>
            <a href="{% url 'kmutnbtrackapp:logout' %}?lab={{ lab_hash }}">
                <button class="dropdown-item" type="button">
                    <img id="checkout_img" src="{% static 'images/logout.png' %}" alt="checkout_pic">
                    ออกจากระบบ
                </button>
            </a>
        </div>
    </div>
</nav>

<!-- check out before due -->
<div class="container">
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">คุณต้องการเช็คเอาท์
            <br><img src="{% static 'images/logo.png' %}"  width="40" alt="lab_pic">{{ last_lab.name }} 
            <br>ก่อนเวลาหรือไม่?
        </h4>
        <hr>
        <p class="mb-0">เวลาเช็คเอาท์จะถูกเปลี่ยนเป็นเวลา ณ ขณะนี้</p>
    </div>
    <div class="alert alert-primary" role="alert">
        <p class="mb-0 showtime">
            <img id="checkin_img" src="{% static 'images/check in.png' %}" alt="checkin_pic">
            เวลาเช็คอินแล็บ {{ last_lab.name }}
            <p class="time-checkin">{{ check_in }}</p>
        </p>
        <p class="mb-0 showtime">
            <img id="checkout_img" src="{% static 'images/logout_2.png' %}" alt="checkout_pic">
            เวลาเช็คเอาท์ที่ระบุ
            <p class="time-checkout">{{ check_out }}</p>
        </p>
    </div>
    <div style="justify-content: center; align-items: center;">
        <button type="button" class="btn btn-danger" style="color:white;width:100%;" onclick="checkout()">
            <img id="checkout_img" src="{% static 'images/logout_2.png' %}" alt="checkout_pic">
            เช็คเอาท์ก่อนเวลา
        </button>
    </div>
</div>
{% endblock %}

kmutnbtrackapp/templates/Page/check_out_prev_lab_before.html
{% extends 'Page/page_base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static '/css/check_out_before_due.css'%}">
{% endblock %}

{% block script %}
<script type="text/javascript"></script>
{% endblock %}

{% block content %}
<!-- navbar room name -->
<nav class="navbar navbar-dark" style="background-color: #1261A0;">
    <a class="navbar-brand" href="#">
        <img src="{% static 'images/logo.png' %}" width="30" height="auto" class="d-inline-block" alt="" loading="lazy">
        {{ lab_name }}
    </a>
    <div class="btn-group btn-username">
        <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="{% static 'images/people.png' %}" width="22" alt="username_pic" >
        </button>
        <div class="dropdown-menu dropdown-menu-right">
            <button class="dropdown-item disabled" type="button">{{ request.user.first_name }}</button>
            <a href="{% url 'kmutnbtrackapp:logout' %}?lab={{ lab_hash }}">
                <button class="dropdown-item" type="button">
                    <img id="checkout_img" src="{% static 'images/logout.png' %}" alt="checkout_pic">
                    ออกจากระบบ
                </button>
            </a>
        </div>
    </div>
</nav>

<div class="container">
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">กรุณาเช็คเอาท์ออกจากแล็บนี้ก่อน : {{ last_lab.name }}</h4>
        <hr>
        <p class="mb-0">เมื่อเช็คเอาท์จากแล็บก่อนหน้าแล้ว ระบบ จะพาคุณไปยัง {{ new_lab.name }}</p>

    </div>
    <div style=" justify-content: center; align-items: center;">
        <a href="{% url 'kmutnbtrackapp:check_out' last_lab.hash %}?next_lab={{ new_lab.hash }}">
            <button type="button" class="btn btn-danger" style="color:white;width: 100%;">
                <img id="checkout_img" src="{% static 'images/logout_2.png' %}" alt="checkout_pic">
                เช็คเอาท์
            </button>


        </a>
    </div>
</div>


{% endblock %}

kmutnbtrackapp/templates/Page/lab_checkin_new.html
{% extends 'Page/page_base.html' %}
{% load static %}

{% block title %}Check in{% endblock %}


{% block style %}
<link rel="stylesheet" type="text/css" href="{% static '/css/lab_checkin.css'%}">
{% endblock %}


{% block script %}
<script type="text/javascript">
    let csrf_token = '{{csrf_token}}'; // Django will render this, don't move to .js file !!!
    const checkin_url = "{% url 'kmutnbtrackapp:check_in' lab_hash  %}";
    const checkout_url = "{% url 'kmutnbtrackapp:check_out' lab_hash  %}";

    selectTime();
    
    function selectTime(){
        const Mode = document.getElementById('time').value;
        const time_selector = document.getElementById('time_value');
        if ( Mode == "others" ){
            time_selector.style.display='block';
        } else {
            time_selector.style.display='none';
            time_selector.value = Mode
        }
    }

    function CheckTime(hour, minute){
        const UserMode = document.getElementById('time').value;
        const UserTime = document.getElementById('time_value');
        let SelectTime = UserTime.value.split(":");
        console.log()
        if (UserMode == "others"){
            if (true) {
                // waiting for beautiful time lock condition
                if (SelectTime[0] >= hour){
                    if (( (SelectTime[1] >= (minute + 10) ) && (SelectTime[0] == hour)) || (SelectTime[0] == (hour + 1) && ( (SelectTime[1] <= 10) && ( (minute + 10) > 60) )) || SelectTime[0] > hour){
                        return true
                    } else {
                        document.getElementById("status").innerHTML = "กรุณาเลือกเวลาที่ถูกต้อง";
                        return false
                    }
                } else {
                    document.getElementById("status").innerHTML = "กรุณาเลือกเวลาที่ถูกต้อง";
                    return false
                }
            } else {
                document.getElementById("status").innerHTML = "กรุณาเลือกเวลาใช้งานที่ถูกต้อง";
                return false
            }
        } 
        else {
            document.getElementById('time_value').value = UserMode
            return true

        }
    }

    $(document).ready(function () {
        var body = $("body")
        $("#checkin_button").click(function (event) {
            if (CheckTime({{time_now_hour}}, {{time_now_minute}}) ){
                $.ajax({
                    headers: { "X-CSRFToken": csrf_token },
                    type: "POST",
                    url: checkin_url,
                    data: {
                        'check_out_time': $("#time_value").val()
                    },
                    success: function (response) {
                        var parser = new DOMParser();
                        var responseHtml = parser.parseFromString(response, "text/html");
                        $("body").html(responseHtml.body)
                        $("#feedbackModal").modal('show')
                        $("#feedbackSubmit").click(function (event) {
                            $("#feedbackModal").modal('hide')
                        })
                    },
                })
            }
        })
    });

    function showModal() {
       // document.getElementById('feedbackModal').style.display='block'
        
    }

    let feedbackApiURL = "{% url 'kmutnbtrackapp:add_feedback' %}"
    function feedbackSubmit()
    {
            let checkedStar = document.querySelector('input[name = "rating"]:checked')
            if (checkedStar != null)
            {
                let selectedRating = checkedStar.value;
                let userComment = document.getElementById("comment").value;

                let data = new FormData();
                data.append("rating", selectedRating)
                data.append("comment", userComment)

                fetch(feedbackApiURL,{
                    method: "POST",
                    headers: { 
                        'X-CSRFToken': csrf_token,
                    },
                    body:data
                })
                .then(response =>{ 

                    console.log(`rating ${selectedRating} submitted!`)
                })
            }
    }
        
    
</script>
{% endblock %}


{% block content %}
<!-- navbar room name -->
<nav class="navbar navbar-dark" style="background-color: #1261A0;">
    <a class="navbar-brand" href="#">
        <img src="{% static 'images/logo.png' %}" width="30" height="auto" class="d-inline-block" alt="" loading="lazy">
        {{ lab_name }}
    </a>
    <div class="btn-group btn-username">
        <button type="button" class="btn dropdown-toggle dropdown-user" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="{% static 'images/people.png' %}" width="22" alt="username_pic" >
        </button>
        <div class="dropdown-menu dropdown-menu-right">
            <button class="dropdown-item disabled" type="button">{{ request.user.first_name }}</button>
            <a href="{% url 'kmutnbtrackapp:logout' %}?lab={{ lab_hash }}">
                <button class="dropdown-item" type="button">
                    <img id="checkout_img" src="{% static 'images/logout.png' %}" alt="checkout_pic">
                    ออกจากระบบ
                </button>
            </a>
        </div>
    </div>
</nav>

<!-- check out before due -->
{% if lab_exceeded_limit %}
    <div class="container" style="text-align: center;">
        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">คำเตือน</h4>
            <p class="time-checkin">ห้องแลปเกินโควต้าที่สามารถเช็คอินได้ ({{ maximum_people }} คน)</p>
            <p class="time-checkin">โปรดแจ้งอาจารย์ประจำแลป เพื่อขออนุญาตทำการเช็คอิน</p>
        </div>
    </div>
{% endif %}
<div class="container">
    <div class="card w-70 mx-auto" style="text-align: center;">
        <div class="card-body">
            <p class="card-text amount-people">
                สวัสดี, {{ request.user.first_name }}
            </p>
            <h5 class="card-title room-name">
                <img src="{% static 'images/logo.png' %}"  width="40" alt="lab_pic">
                {{ lab_name }}
            </h5>
            <p class="card-text amount-people">
                <img src="{% static 'images/people.png' %}"  width="22" alt="lab_pic">
                จำนวนคนในแลปขณะนี้ : {{ current_people }} คน
            </p>
            <form id="TimeForm">

                {% csrf_token %}
                <input name="next" id="lab_hash" value="{{lab_hash}}" hidden>
                <label for="check_out_time" class="checkout_select_time">เลือกเวลาเช็คเอาท์ :</label> 
            
                <div class="dropdown checkout_time">
                    
                    <select class="btn btn-light btn-sm dropdown-toggle btn-timeselect" aria-haspopup="true" aria-expanded="false" aria-labelledby="dropdownMenu2" id="time" onchange='selectTime();'>
                        {% if time_option == 1 %}
                            <option selected="selected" value="12:00">12:00</option>
                            <option value="16:00">16:00</option>
                            <option value="20:00">20:00</option>
                            <option value="others">กำหนดเอง</option>
                        {% elif time_option == 2 %}
                            <option selected="selected" value="16:00">16:00</option>
                            <option value="20:00">20:00</option>
                            <option value="others">กำหนดเอง</option>
                        {% elif time_option == 3 %}
                            <option selected="selected" value="20:00">20:00</option>
                            <option value="others">กำหนดเอง</option>
                        {% elif time_option == 4 %}
                            <option selected="selected" value="others">กำหนดเอง</option>
                        {% endif %}
                    </select>
                    
                </div>
                
                <br>
                
                <div class="container-fluid col-12 col-sm-4">
                    <div class="form-group input-time">
                        
                      <input type="time" class="form-control" name="check_out_time" id="time_value" value="12:00" onchange="CheckTime({{time_now_hour}}, {{time_now_minute}}) " style='display:none;'/>
                    </div>
                </div>

            
                <p id="status"></p>
                <div>
                    <button style="width:100%" type="button" class="btn btn-success btn-checkin" id="checkin_button">เช็คอิน</button>
                </div>

            </form>
        </div>
    </div>
</div>

{% endblock %}